class StaticVariable:
    TestAddition = "./src/Tests/BasicFunctions/Addition.csv"
    TestSubtraction = "./src/Tests/BasicFunctions/Subtraction.csv"
    TestMultiplication = "./src/Tests/BasicFunctions/Multiplication.csv"
    TestDivision = "./src/Tests/BasicFunctions/Division1.csv"
    TestSquare = "./src/Tests/BasicFunctions/Square.csv"
    TestSquareRoot = "./src/Tests/BasicFunctions/SquareRoot.csv"
    value1 = "Value 1"
    value2 = "Value 2"
    result = "Result"
